// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJoVwZNOh30PgOE7kcPsoIzn6IPZIIZbU',
    appId: '1:697674735032:web:7715464be87918f0d4034d',
    messagingSenderId: '697674735032',
    projectId: 'sampleapp-661d2',
    authDomain: 'sampleapp-661d2.firebaseapp.com',
    storageBucket: 'sampleapp-661d2.appspot.com',
    measurementId: 'G-1LJLCBK258',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqym5bVcQ8ywWkyq2dsQ43prCu8mQNPY',
    appId: '1:697674735032:android:141557f4fab1f4d4d4034d',
    messagingSenderId: '697674735032',
    projectId: 'sampleapp-661d2',
    storageBucket: 'sampleapp-661d2.appspot.com',
  );
}
